version: "3.9"

services:
  api:
    build: .
    container_name: kwh-btc-iot-api
    ports:
      - "8000:8000"
    environment:
      - KWH_BTC_IOT_API=http://api:8000
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: kwh-btc-iot-mqtt
    ports:
      - "1883:1883"
